# Generated by Django 3.2.4 on 2022-03-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user1ReadReceipt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2ReadReceipt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
