# Generated by Django 3.2.4 on 2022-04-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_auto_20220324_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isReadByOther',
            field=models.BooleanField(default=False),
        ),
    ]
