# Generated by Django 3.2.4 on 2022-04-02 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0003_message_isreadbyother'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user1ReadReceipt',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user2ReadReceipt',
        ),
    ]
